### ISSUE TITLE
Unable to start the Python language server

### ISSUE THREAD

**Issue by akashbhanu009** [atom-community/ide-python#134]
![2018-08-07 1](https://user-images.githubusercontent.com/33896992/43768268-ce68703e-99eb-11e8-9409-bc5ec57efa2c.png)

**Comment by unparadise** [comment]
I have the same issue on my Mac. I used the command line instruction to make sure that the python-language-server is up to date. But the next time I launch Atom, the prompt shows up again.

I am also not exactly sure whether I need to use pip or pip3 since the python code I have is in Python3 format.

Help please.

Best,
Frank

**Comment by extraymond** [comment]
If your python path is not in the system path, you need to launch atom with the correct virtual-env. Hope this helps.

**Comment by unparadise** [comment]
@extraymond  Hi extraymond, thank you for trying to help. I have checked the bash setup file and pyls is included in the PATH. So, I am not sure what's causing this issue.

**Comment by unparadise** [comment]
I did get the following error message when I tried to install pyls again.

"Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-DvzR6D/python-language-server/"

I tried to look it up on Google but found nothing.

**Comment by leoburgy** [comment]
@figa17 Did you try @ssanalk fix? I replaced in the IDE Python Settings/Python Executable 'python' with python3, restarted atom and the everything was fixed.

**Comment by nagromc** [comment]
> 
> 
> @figa17 Try downgrading python-language-server to version 0.19.0:
> 
> ```
> pip install python-language-server==0.19.0
> ```
> 
> This is the last version that works work me. Sadly, this Atom module seems to be abandoned. We really need a working Python IDE module for Atom.

Actually, a more recent version does work with `ide-python`: 0.20.0

```
pip install python-language-server==0.20.0
```

**Comment by extraymond** [comment]
Hi! I think this might be a bug!!! After fiddling with updating python-language-server version, it seems that there was a api breakage  between python-language-server and ide-python. I finally get this working again without needing to jump back to 0.10.

After opening up the inspector, I found that its bugging about jsonrpc related stuff not found in the distribution. And after finding the change log of python-language-server, there seems to be a change regarding jsonrpc.

I assume ide-python follows python-language-server closely, so this might be the case for people with weird behavior.

[json-rpc related changes in the changelog](https://github.com/palantir/python-language-server/releases/tag/0.21.5)

This starts in version 0.21.5, as a result, ide-python might need a newer python-language-server to work. I'm not 100% sure about the combination required to do so though.

**Comment by cscomic** [comment]
> @figa17 Try downgrading python-language-server to version 0.19.0:
> 
> ```
> pip install python-language-server==0.19.0
> ```
> This is the last version that works work me. Sadly, this Atom module seems to be abandoned. We really need a working Python IDE module for Atom.

not works for me 

anaconda python 2
windows 10

**Comment by sanidhya1996** [comment]
i am having this problem in using python in atom on windows. i have pip vr1903 installed.
![atom](https://user-images.githubusercontent.com/49881607/56519238-33fc9300-655f-11e9-9aa2-98d9d0aecc0b.png)

**Comment by kevart** [comment]
Same issue. Virtual environment exists and has the required packages installed.

ide-python 1.4.1
python executable set to `$PROJECT/env/bin/python`

cd <project>
which python
> <project>/env/bin/python
python --version
>Python 3.7.3
python -m pyls --help
> usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT] ..

**Comment by ShnitzelKiller** [comment]
I have the same problem with anaconda python 3 on OS X. Above fixes do not work.

**Comment by naff1x** [comment]
> I had the same issue on my Mac as well. I solved it by going into the settings of ide-python and setting the 'Python Executable' to python3 instead of python.

Thank you, this seems to work for me! Just to clarify for others, you can find this setting in the file "package.json" at ` "default": "python"`.

![Screen Shot 2019-06-09 at 19 24 13](https://user-images.githubusercontent.com/32478262/59162133-3e152980-8aec-11e9-9d22-9508892b2f4a.png)

**Comment by bionicles** [comment]
same

**Comment by extraymond** [comment]
Guys! If you still have this problem, please first check the dependency of python-language-server, there are some dependency changes that caused the malfunctioning.

Please first check the following step:
1. Check the error log in the debug mode in atom if you encounter an error. (ctrl-shit-i)
2. If you see jsonrpc related error log, go check your python-language-server version.
3. Make sure that it is using python-jsonrpc-server instead of the package jsonrpc.
4. I believe you have to upgrade python-langauge-server beginning with version started from 0.21.5.

As always, please provide debug message from atom-ide, it would make it easier for all of us to find out what happened.

**Comment by meetgeorge** [comment]
I solved it,by open Preferences(Cntrl+Comma) -> Open Config Folder -> packages -> ide-python -> package.json -> search(Cntrl+f) for "python executable" -> inside the same object look for "default" -> change it's value from "python" to "python3", save and restart Atom.

eg:
`python": {
      "title": "Python Executable",
      "order": 1,
      "type": "string",
      "default": "python3",
      "description": "Absolute path of your Python binary. This is used to launch the Python language server. Make sure to install `pyls` for this version of Python. Changes will take effect after a restart of the language server. Use $PIPENV_PATH if you want to use the pipenv path of your project"
    },`

**Comment by lucosmic** [comment]
This is probably the most informative thread on this general issue! Thank you! 
I'm still having trouble on my Linux Mint machine. pyls boots from the bash console with Python 3. The python executable was changed to python3 as per meetgeorge's suggestion and I opened the error log like extraymond suggested. Still getting errors.

![Screenshot](https://user-images.githubusercontent.com/49736250/60075614-f513c680-96e2-11e9-892b-cf4b124b5271.png)


Also, when I disabled/enabled the program a few times, I got these errors:

![Screenshot2](https://user-images.githubusercontent.com/49736250/60075641-052ba600-96e3-11e9-8d65-2c1a6cd84c69.png)


It says it failed to shutdown the pyls... Does this imply that pyls actually started? Perhaps my issues are more closely related to this issue: https://github.com/lgeiger/ide-python/issues/119 where the loading wheel is taking forever.

**Comment by lucosmic** [comment]
This is probably the most informative thread on this general issue! Thank you! 
I'm still having trouble on my Linux Mint machine. pyls boots from the bash console with Python 3. The python executable was changed to python3 as per meetgeorge's suggestion and I opened the error log like extraymond suggested. Still getting errors.

![Screenshot](https://user-images.githubusercontent.com/49736250/60075614-f513c680-96e2-11e9-892b-cf4b124b5271.png)


Also, when I disabled/enabled the program a few times, I got these errors:

![Screenshot2](https://user-images.githubusercontent.com/49736250/60075641-052ba600-96e3-11e9-8d65-2c1a6cd84c69.png)


It says it failed to shutdown the pyls... Does this imply that pyls actually started? Perhaps my issues are more closely related to this issue: https://github.com/lgeiger/ide-python/issues/119 where the loading wheel is taking forever. 

EDIT: Somehow I fixed it by re-installing Atom straight from the .deb package on atom.io . I must have gotten the faulty distro of Atom from the Package Manager. I noticed my original install had no `apm` program installed for Atom.

**Comment by theofilos13** [comment]
1.  **Set up interpreter** 
- If you are at a virtual env, first you have to set yours environment's interpreter (_".../env_name/Scripts/python.exe"_ for WIN or [here](https://stackoverflow.com/questions/2589711/find-full-path-of-the-python-interpreter)) to IDE Python -> Python Executable. 
- Otherwise you set your "default" interpreter, located (by default) in _".../Program Files/PythonXX/python.exe"_ for WIN, or [here](https://stackoverflow.com/questions/2589711/find-full-path-of-the-python-interpreter). 

- If you restart atom and the problem continues to exist, you have to install the python-language-server(_pyls_) with the interpreter you set at IDE Python -> Python Executable. 

2. **Install python-language-server**
- If you are using the default interpreter, just run `pip install python-language-server[all]` 
or `python -m pip install 'python-language-server[all]'`

- Virtual Env: [Activate your virtual env](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/26/python-virtual-env/) on a terminal and run `pip install python-language-server[all]` 
or `python -m pip install 'python-language-server[all]'`

**Comment by bchanson** [comment]
If anyone else runs into this. [This](https://github.com/palantir/python-language-server/issues/658) is what solved it for me.... 

"The issue was probably that I have installed pip install pyls first and then pip install python-language-server.

So I have just uninstall pyls and python-language-server and installed only python-language-server."

**Comment by rydlin** [comment]
Start atom from the terminal with a Python virtual environment activated and language server installed solved it for me
`(pyenv): atom . `
Starting atom from Debian Gnome GUI was not working correctly

**Comment by wsandrews** [comment]
> If anyone else runs into this. [This](https://github.com/palantir/python-language-server/issues/658) is what solved it for me....
> 
> "The issue was probably that I have installed pip install pyls first and then pip install python-language-server.
> 
> So I have just uninstall pyls and python-language-server and installed only python-language-server."

This is what fixed the issue for me.

**Comment by d-simple** [comment]
I've had a 'logging' module in my project dir. When pyls tried to start, it was referencing my module instead of standard lib's and crashed.

**Comment by Jest0r** [comment]
My problem was that I had PlatformIO installed, too. and it used another python binary...
![image](https://user-images.githubusercontent.com/22813091/74514771-899a9580-4f0d-11ea-98fe-65d7c1d228a8.png)
Disabling PlatformIO or installing in it's own venv solved the problem.
> ~/.platformio/penv/bin/python3 -m pip install 'python-language-server[all]'

**Comment by sivizius** [comment]
Solved with replacing statement beginning at line 60 in packages/ide-python/lib/main.js with `const childProcess = cp.spawn("pyls");`, not nice, but works for me

**Comment by aalexbugheanu** [comment]
Solved by running this commands from Win PowerShell:

python -m pip install 'python-language-server[all]'
apm install atom-ide-ui
apm install ide-python

**Comment by metalaxe64** [comment]
> Solved by running this commands from Win PowerShell:
> 
> python -m pip install 'python-language-server[all]'
> apm install atom-ide-ui
> apm install ide-python

Solved this exact problem for me --- THANK YOU!!!

**Comment by RayXeon** [comment]
> Solved by running this commands from Win PowerShell:
> 
> python -m pip install 'python-language-server[all]'
> apm install atom-ide-ui
> apm install ide-python

Works on my mac as well. Sincere gratitude.

**Comment by zilbert97** [comment]
I found a solution which involved updating python via homebrew and pyenv - https://github.com/lgeiger/ide-python/issues/85#issuecomment-711290350

**Comment by red181526** [comment]
I FOUND A SOLUTUION!
Windows 10 - atom - python3.9

funny, but i just run this: "pip install python-language-server"
I don't know why it's not installed!!!

> 
> 
> i am having this problem in using python in atom on windows. i have pip vr1903 installed.
> ![atom](https://user-images.githubusercontent.com/49881607/56519238-33fc9300-655f-11e9-9aa2-98d9d0aecc0b.png)

**Comment by GGurtner** [comment]
Still not working on my side. I'm on Mint 20 and I am not using a virtual env but I can't figure out how to make this work. Changing the python executable to python3 (that I normally use) does not help. This answer:

> I had the same error with python 3.
> The issue was probably that I have installed pip install pyls first and then pip install python-language-server.
> So I have just uninstall pyls and python-language-server and installed only python-language-server.
> Now pyls runs ok.

does not help either. The log says "/usr/bin/python3: No module named pyls". Even when I do `sudo pip3 install pyls` it does not work better... Anyone has an idea?

**Comment by ptousignant** [comment]
Don't `pip install pyls`. That's not the Python Language Server, despite matching the executable name. You must use `pip install python-language-server`. You probably want `pip install python-language-server[all]` so that all of the additional modules it depends on are also installed.

I recommend you do this in a virtualenv and then, in Atom's Ide Python package config, point the `Path to pyls executable` to the Python executable inside the virutalenv. This is what mine looks like, for example.

![image](https://user-images.githubusercontent.com/43143024/124392729-e17d9c00-dcbc-11eb-9a1f-d36c3ae348e9.png)

Here, `/home/ptous/venvs` is where all my virutalenv directories live, and `pyls` is the name of the one where I install the language server.
