### ISSUE TITLE
Update to Python 3.10 match-case construction

### ISSUE THREAD

**Issue by maleksware** [atom-community/ide-python#427]
Will ide-python be updated for Python 3.10? If no, why?

**Comment by asdorsey** [comment]
I'm attempting to move to Atom from VSCodium since Microsoft blocks PyLance support on non-MS builds, and the Jedi language server doesn't support Python 3.10's `match` statement (https://github.com/davidhalter/jedi/issues/1843).  Unfortunately, it looks like Atom has the same issue, since it also uses Jedi for Python syntax checking.
