### ISSUE TITLE
Update of lint errors is too slow

### ISSUE THREAD

**Issue by qherreros** [atom-community/ide-python#56]
![toto](https://user-images.githubusercontent.com/7406885/34102930-28f855b2-e3eb-11e7-9d18-b1bf4e79053b.png)

Here is a screenshot to illustrate my issue. Time to time, some lint errors are still here even if the issue has been fixed. Not sure how to reproduce this exactly but it seems to happen regularly. I'm using Atom 1.23, pyls 0.12 in python3 on Linux.

A frustrating fix is to type something and delete it to "update" lint.

Cheers

**Comment by culhatsker** [comment]
Same thing happens to me from time to time when I save the file at the same moment as I made the changes.

**Comment by tweakimp** [comment]
How to reproduce:
1) Use a beautifier like atom-beautify.
2) Activate beautify on save.
3) Have a lint error and save.
4) Linter doesnt update because no user input has been made, but error is gone and error message is still there.

**Comment by lgeiger** [comment]
@tweakimp I can't reproduce this with either `atom-beautify` or the `pyls` code formatting.
I'm using the dev version of `python-language-server` and the latest versions of Atom, `ide-python` and `atom-ide-ui`.

@tweakimp @Paradoxeuh, @culhatsker Could you enable debug messages by executing `atom.config.set('core.debugLSP', true)` in the Developer Tools Console and post a screenshot of the console output when this issue occurs? You might need to restart Atom in order to see the debug messages.

**Comment by lgeiger** [comment]
There've been a lot of performance improvements in the latest release of the language server.

Could you check if this is still reproducible with `python-language-server==0.17.0` and `ide-python==0.9.0`?

To upgrade the server run:
```shell
pip install 'python-language-server[all]' --upgrade
```

**Comment by floydwch** [comment]
@lgeiger same issue here
![mDp0SXNA](https://user-images.githubusercontent.com/1651509/67154619-2c614f80-f332-11e9-8ddd-81d9f648fd56.png)
